#!/bin/bash
# Demo script for GoodWe Dynamic Price Optimiser

echo "🚀 GoodWe Dynamic Price Optimiser - Demo Mode"
echo "=============================================="
echo ""

# Activate virtual environment
source venv/bin/activate

echo "📦 Python Environment:"
echo "  Python version: $(python --version)"
echo "  Virtual environment: $(which python)"
echo ""

echo "📁 Project Structure:"
echo "  Source code: src/"
echo "  Configuration: config/"
echo "  Scripts: scripts/"
echo "  Documentation: docs/"
echo ""

echo "🔧 Available Components:"
echo "  - Master Coordinator (main orchestrator)"
echo "  - Enhanced Data Collector"
echo "  - Fast Charge Controller"
echo "  - Polish Electricity Analyzer"
echo "  - Automated Price Charging"
echo ""

echo "⚙️  Configuration:"
echo "  Inverter IP: 192.168.68.51 (configured but not accessible in demo)"
echo "  Battery: 2x GoodWe Lynx-D LX-D5.0-10 (20kWh LFP)"
echo "  PV System: 6.8kW maximum"
echo "  Charging: Up to 5kW with safety limits"
echo ""

echo "🎯 Key Features:"
echo "  - Dynamic electricity price optimization"
echo "  - Battery safety compliance (GoodWe Lynx-D)"
echo "  - PV production monitoring"
echo "  - Grid flow analysis"
echo "  - Automated charging decisions"
echo ""

echo "📊 Decision Engine Weights:"
echo "  - Electricity Price: 40%"
echo "  - Battery State: 25%"
echo "  - PV Production: 20%"
echo "  - House Consumption: 15%"
echo ""

echo "🛡️  Safety Features:"
echo "  - Battery temperature monitoring (0-53°C)"
echo "  - Voltage range protection (320-480V)"
echo "  - Current limiting (max 32A)"
echo "  - Emergency stop conditions"
echo "  - VDE 2510-50 compliance"
echo ""

echo "📈 Data Management:"
echo "  - 30-day data retention"
echo "  - Automated backups"
echo "  - Performance monitoring"
echo "  - Log rotation"
echo ""

echo "🐳 Docker Support:"
echo "  - Dockerfile available"
echo "  - Docker Compose configuration"
echo "  - Health checks"
echo "  - Resource limits"
echo ""

echo "📋 Management Commands:"
echo "  python src/master_coordinator.py --help"
echo "  python src/master_coordinator.py --status"
echo "  python src/master_coordinator.py --test"
echo "  ./scripts/docker_manage.sh help"
echo ""

echo "✅ Setup Complete!"
echo ""
echo "The GoodWe Dynamic Price Optimiser is ready to use."
echo "In a real environment, it would connect to your GoodWe inverter"
echo "and optimize battery charging based on electricity prices."
echo ""
echo "For production deployment:"
echo "1. Update config/master_coordinator_config.yaml with your inverter IP"
echo "2. Run: python src/master_coordinator.py"
echo "3. Or use Docker: docker-compose up -d"
echo ""