# GoodWe Inverter Fast Charging Configuration
# Copy this file to fast_charge_config.yaml and modify the values

# Inverter Network Configuration
inverter:
  # IP address of your GoodWe inverter
  ip_address: "192.168.68.51"
  # Port (usually 8899 for GoodWe inverters, 502 for TCP)
  port: 8899
  # Inverter family (ET, ES, DT, or null for auto-detect)
  family: "ET"
  # Communication address (usually 0xf7 for ET/ES, 0x7f for DT, or null for default)
  comm_addr: 0xf7
  # Network timeout in seconds
  timeout: 1
  # Number of retry attempts
  retries: 3

# Fast Charging Parameters
fast_charging:
  # Enable fast charging (true/false)
  enable: true
  # Charging power as percentage (0-100)
  power_percentage: 90
  # Target State of Charge percentage (0-100)
  target_soc: 100
  # Maximum charging time in minutes (0 for unlimited)
  max_charging_time: 120

# Safety Settings
safety:
  # Maximum battery temperature in Celsius (0 to disable)
  max_battery_temp: 50
  # Minimum battery SoC before starting charge (0-100)
  min_battery_soc: 10
  # Maximum grid power usage in watts (0 to disable)
  max_grid_power: 5000

# Logging Configuration
logging:
  # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  level: "INFO"
  # Log to file (true/false)
  log_to_file: true
  # Log file path
  log_file: "fast_charge.log"

# Notification Settings
notifications:
  # Send notifications when charging starts/stops (true/false)
  enabled: false
  # Webhook URL for notifications (optional)
  webhook_url: ""
  # Email settings (optional)
  email:
    smtp_server: ""
    smtp_port: 587
    username: ""
    password: ""
    from_email: ""
    to_email: ""

