"""add market prices

Revision ID: 5a2c3d4e5f6g
Revises: 24e05aea8977
Create Date: 2026-01-11 20:45:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a2c3d4e5f6g'
down_revision = '24e05aea8977'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_prices',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('price_pln_mwh', sa.Float(), nullable=False),
        sa.Column('source', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_prices_timestamp'), 'market_prices', ['timestamp'], unique=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_prices_timestamp'), table_name='market_prices')
    op.drop_table('market_prices')
    # ### end Alembic commands ###
