#!/bin/bash
set -e

# Secure Secret Setup Script
# Usage: ./manage-secrets.sh [vps|rasp]

TARGET="${1:-vps}"

# Configuration
VPS_HOST="root@srv26.mikr.us"
VPS_PORT="10358"
RASP_HOST="rmachnik@192.168.33.10"
RASP_PORT="22"

if [ "$TARGET" = "vps" ]; then
    HOST="$VPS_HOST"
    PORT="$VPS_PORT"
    REMOTE_DIR="/home/goodwe/goodwe-cloud-hub/hub-api"
    ENV_FILE=".env"
    USER="goodwe"
elif [ "$TARGET" = "rasp" ]; then
    HOST="$RASP_HOST"
    PORT="$RASP_PORT"
    REMOTE_DIR="~/sources/goodwe-dynamic-price-optimiser"
    ENV_FILE=".env"
    USER="rmachnik" # Or current user
else
    echo "Usage: $0 [vps|rasp]"
    exit 1
fi

echo "🔐 Securely configuring secrets for $TARGET..."
echo "   Host: $HOST"
echo ""

# Function to prompt securely
read_secret() {
    local prompt="$1"
    local var_name="$2"
    echo -n "$prompt"
    read -s input
    echo ""
    eval "$var_name='$input'"
}

# 1. Database Credentials
echo "--- Database Configuration ---"
read -p "Database Host [psql01.mikr.us]: " DB_HOST
DB_HOST=${DB_HOST:-psql01.mikr.us}

read -p "Database User [andrzej358]: " DB_USER
DB_USER=${DB_USER:-andrzej358}

read_secret "Database Password: " DB_PASS

read -p "Database Name [db_andrzej358]: " DB_NAME
DB_NAME=${DB_NAME:-db_andrzej358}

# Construct Database URL
DATABASE_URL="postgresql+asyncpg://$DB_USER:$DB_PASS@$DB_HOST:5432/$DB_NAME"


# 2. RabbitMQ/MQTT Credentials
echo ""
echo "--- MQTT Broker Configuration ---"
read -p "MQTT Host [mws03-52071.wykr.es]: " MQTT_HOST
MQTT_HOST=${MQTT_HOST:-mws03-52071.wykr.es}

# Default MQTT port for SSL is usually 8883, plain 1883
# Since it's a managed service, we should ask.
read -p "MQTT Port (SSL recommended: 8883, Plain: 1883) [1883]: " MQTT_PORT
MQTT_PORT=${MQTT_PORT:-1883}

echo "Enter the MQTT User for the Hub API (the one the Hub will use to connect)"
read -p "MQTT Hub User [hub_api]: " MQTT_USER
MQTT_USER=${MQTT_USER:-hub_api}

read_secret "MQTT Hub Password: " MQTT_PASS


# 3. Security Keys
echo ""
echo "--- Application Security ---"
read -p "Generate new JWT Secret? [y/N]: " GEN_JWT
if [[ "$GEN_JWT" =~ ^[Yy]$ ]]; then
    JWT_SECRET=$(openssl rand -hex 32)
    echo "Generated new secure JWT key."
else
    read_secret "Enter existing JWT Secret: " JWT_SECRET
fi


# 4. Write to Remote Server
echo ""
echo "📤 Uploading configuration to $HOST..."

# We use ssh to write the file directly on the remote server, preventing local temp file storage of secrets
# NOTE: We preserve existing keys if we were being fancy, but here we overwrite for specific sensitive vars
# or simply append/create.
# Safer strategy: Create the full .env content in memory and pipe it to ssh.

# Prepare Env Content
ENV_CONTENT=$(cat <<EOF
# Production Environment Configuration
# Generated by manage-secrets.sh on $(date)

# Database
DATABASE_URL=$DATABASE_URL

# MQTT
MQTT_BROKER=$MQTT_HOST
MQTT_PORT=$MQTT_PORT
MQTT_USER=$MQTT_USER
MQTT_PASS=$MQTT_PASS

# Security
JWT_SECRET_KEY=$JWT_SECRET

# CORS (Including VPS direct access and localhost for testing)
CORS_ORIGINS=http://localhost:5173,http://localhost:5174,http://srv26.mikr.us,http://srv26.mikr.us:40314,http://srv26.mikr.us:40315

# Admin Email (for initial setup)
ADMIN_EMAIL=admin@example.com
EOF
)

# Execute upload
ssh -p "$PORT" "$HOST" "mkdir -p $REMOTE_DIR && cat > $REMOTE_DIR/$ENV_FILE" <<EOF
$ENV_CONTENT
EOF

echo "✅ Configuration successfully written to $REMOTE_DIR/$ENV_FILE on $TARGET."
echo "⚠️  Restart the service for changes to take effect."
